### ISSUE TITLE
where is SessionFactory? I can`t find it in the repo.

### ISSUE THREAD

**Issue by 188867052** [1448376744/Dapper.Linq#4]
where is SessionFactory? I can`t find it in the repo.

**Comment by chenlike** [comment]
use DbContextFactory

**Comment by 1448376744** [comment]
You can see the source code of the corresponding version. Session in the new version is renamed DbContext. Tomorrow we will update the document, add sub-queries, customize Sql statement blocks, and other functions. Thank you for your support!
