### ISSUE TITLE
关于实体主键的问题

### ISSUE THREAD

**Issue by qesadwzxc** [1448376744/Dapper.Linq#9]
我知道实体属性添加了[Column()]后则标识为主键，insert时会忽略这个属性
但是我的主键是guid，我看到模板实体里面ColumnAttribute有个Extra参数可以标识该字段是否自增，现在为什么去掉了呢？
现在如果我想实现insert时不排除加了IsIdentity = true的属性该怎么做呢？

**Comment by 1448376744** [comment]
#
